version: "3"
services:
  pantip-scraper:
    build: .
    volumes:
      - "./:/home/yuck/pantip-scraper:rw"
      - "/home/yuck/pantip-scraper/node_modules"
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:dev"]
    depends_on:
      - mongodb
    restart: always
  mongodb:
    build: ./mongodb
    image: yuck/pantip-scrape-db
    ports:
      - "27017:27017"
  mongo-unit-test:
    build: ./mongodb
    image: yuck/pantip-scarpe-unittest
    ports:
      - "27019:27017"
